swagger: '2.0'
info:
    title: Address Book
    version: 0.1.1
consumes:
    - application/json
produces:
    - application/json
schemes:
    - http
host: localhost:8765
securityDefinitions:
    api_key:
        type: apiKey
        in: header
        name: API-Key
security:
    -
        api_key: []
paths:
    /contacts:
        get:
            summary: List contacts
            responses:
                default: {$ref: '#/responses/Error'}
                '200':
                    description: Contacts list
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Contact'

        post:
            summary: Add contact
            parameters:
                -
                    name:     contact
                    in:       body
                    required: true
                    schema:
                        $ref: '#/definitions/Contact'
            responses:
                default: {$ref: '#/responses/Error'}
                '201':
                    description: Added contact
                    schema:
                        $ref: '#/definitions/Contact'

responses:
    # Return general errors using same model as used by go-swagger for validation errors.
    Error:
        description: Error
        schema:
            $ref: '#/definitions/Error'

definitions:
    # This model should match output of api.ServeError handler, to ensure
    # errors returned by go-swagger (like failed validation) use same
    # format as general errors returned by our handlers.
    # By default api.ServeError = github.com/go-openapi/errors.ServeError.
    Error:
        type: object
        required:
            - code
            - message
        properties:
            code:
                description: Either same as HTTP Status Code OR >= 600 with HTTP Status Code 422
                type: integer
                format: int32
            message:
                type: string

    Contact:
        type: object
        required:
            - name
        properties:
            id:
                type: integer
                format: int32
                readOnly: true
            name:
                type: string
                minLength: 1
